version: '3.7'
services:

  jupyter:
    build:
      context: ./dockerfile
      dockerfile: dockerfile-jupyter
    container_name: jupyter
    hostname: jupyter
    expose:
      - "8888"
    ports:
      - "8888:8888"
      - "5000:5000"
    command: start-notebook.sh --NotebookApp.token=''
    volumes:
      - /iii/jupyter:/home/jovyan/webhook-dev
    networks:
      iii_net:
        ipv4_address: 172.28.1.2

  hadoop:
    image: orozcohsu/ha-sp-ze-zo-hi-fl-rs-ma-sq
    container_name: hadoop
    hostname: master
    environment:
      - "NODE_TYPE=master"
    expose:
      - "50070"
      - "9000"
    ports:
      - "8088:8088"
      - "50070:50070"
      - "9000:9000"
      - "2222:22"
      - "28080:28080"
      - "18080:18080"
      - "10000:10000"
      - "10002:10002"
      - "9083:9083"
      - "3306:3306"
    volumes:
      - /tmp/docker-cluster-hadoop-name/:/data/dfs/name/
      - /tmp/docker-cluster-hadoop-data/:/data/dfs/data/
      - /tmp/docker-cluster-hadoop-logs/:/usr/local/hadoop/logs/
      - /tmp/docker-cluster-zookeeper-logs/:/var/log/zookeeper/
      - /tmp/docker-cluster-zeppelin-logs/:/usr/local/zeppelin/log
    networks:
      iii_net:
        ipv4_address: 172.28.1.3
networks:
    iii_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
